services:
  - type: web
    name: trivion
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.principal:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /api/saude
